spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    url: jdbc:mysql://localhost:3306/shirt
    password: manoj@123
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: 'true'
Welcome:
  message: welcome to manoj spring boot class


